<a href="https://colab.research.google.com/github/Nishnat14/Big-Data-MCA-/blob/main/assingment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#1
import numpy as np
arr = np.array([1, 2, 3, 6, 4, 5])
arr_rev=arr[::-1]
print(arr_rev)

[5 4 6 3 2 1]


In [ ]:
#2
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])
print(arr1==arr2)

[[ True  True]
 [ True  True]]


In [5]:
#3

import numpy as np
def number(arr):
  maxCount=0
  for i in range(len(arr)):
    count=1
    for j in range(i+1,len(arr)):
      if arr[i]==arr[j]:
        count=count+1
    if(maxCount<count):
      maxCount=count
      num=arr[i]
  return num


x=np.array([1,2,3,4,5,1,2,1,1,1])
y=np.array([1,1,1,2,3,4,2,4,3,3])
num1=number(x)    #most frequent number in array x
num2=number(y)    #most frequent number in array y
print("Number most frequent in array x:",num1)
print("Indexes:")
for i in range(len(x)):
  if x[i]==num1:
    print(i,end=' ')
print("\nNumber most frequent in array y:",num2)
print("Indexes:")
for i in range(len(y)):
  if y[i]==num2:
    print(i,end=' ')

Number most frequent in array x: 1
Indexes:
0 5 7 8 9 
Number most frequent in array y: 1
Indexes:
0 1 2 

In [ ]:
 gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
addition=np.sum(gfg)
print(addition)
add_row=np.sum(gfg,axis=1)
print(add_row)
add_col=np.sum(gfg,axis=0)
print(add_col)

45
[[14]
 [16]
 [15]]
[[20  9 16]]
