<a href="https://colab.research.google.com/github/Nishnat14/Big-Data-MCA-/blob/main/assingment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#1
import numpy as np
arr = np.array([1, 2, 3, 6, 4, 5])
arr_rev=arr[::-1]
print(arr_rev)

[5 4 6 3 2 1]


In [ ]:
#2
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])
print(arr1==arr2)

[[ True  True]
 [ True  True]]


In [ ]:
#3
x = np.array([1,2,3,4,5,1,2,1,1,1])
mode=np.mode(x)
print(mode)
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])
m=np.mode(y)
print(y)

AttributeError: module 'numpy' has no attribute 'mode'

In [ ]:
 gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
addition=np.sum(gfg)
print(addition)
add_row=np.sum(gfg,axis=1)
print(add_row)
add_col=np.sum(gfg,axis=0)
print(add_col)

45
[[14]
 [16]
 [15]]
[[20  9 16]]
