<a href="https://colab.research.google.com/github/Nishnat14/Big-Data-MCA-/blob/main/labeval_group2_202301040.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
array=np.array([10,52,62,16,16,54,453])


In [18]:

array2=np.sort(array)
print(array2)

[ 10  16  16  52  54  62 453]


In [5]:

sorted_indices = np.argsort(array)
print(sorted_indices)


[0 3 4 1 5 2 6]


In [20]:

smallest_elements = array2[:4]
print(smallest_elements)


[10 16 16 52]


In [22]:


largest_5_elements = array[sorted_indices[-5:]]
print(largest_5_elements)


[ 16  52  54  62 453]
